stages:
  - test
  - build
  - publish

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

default:
  before_script:
    - mkdir -p ~/.gradle
    - |
      cat <<EOF >> ~/.gradle/gradle.properties
      gitLabPrivateToken=${CI_JOB_TOKEN}
      gitLabUserName=Job-Token
      EOF

pages:
  image: cimg/android:2025.04
  only:
    - tags
    - web
  tags:
    - docker
  stage: publish
  script:
    - sudo apt-get update
    - sudo apt-get install -y pandoc
    - make pages
  artifacts:
    paths:
      - public
  cache:
    key: "$CI_COMMIT_REF_NAME"
    paths:
      - .gradle

publish:
  image: cimg/android:2025.04
  stage: publish
  only:
    - tags
  tags:
    - docker
  script:
    - ./gradlew --no-daemon publish
