name: AAR

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    permissions:
      contents: write
      discussions: write
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build aar
        run: ./gradlew :kinegram-emrtd-connector:assembleRelease
      - name: Rename aar to include version
        run: >
          mv kinegram-emrtd-connector/build/outputs/aar/kinegram-emrtd-connector-release.aar 
          "kinegram-emrtd-connector-$GITHUB_REF_NAME.aar"
      - name: Extract Changes from CHANGELOG.md
        run: |
          CHANGES=$(awk -v version="## $GITHUB_REF_NAME" '{
             if ($0 ~ "^## " && found) exit;
             if (found) print;
             if ($0 == version) found=1;
          }' CHANGELOG.md)
          if [ -n "$CHANGES" ]; then
            echo -e "### Changes\n$CHANGES" > "CHANGELOG-$GITHUB_REF_NAME.md"
          else
            echo "No changes found for version $GITHUB_REF_NAME."
          fi
      - name: Github Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "CHANGELOG-${{ github.ref_name }}.md"
          body: ""
          files: "kinegram-emrtd-connector-${{ github.ref_name }}.aar"
